In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from apyori import apriori

In [5]:
transactions = pd.read_csv("./store_data.csv", header=None)
transactions.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
no_transactions = len(transactions)
max_items_per_transactions = len(transactions.columns)
records = []
for i in range(0, no_transactions):
    records.append([
        str(transactions.values[i, j]) 
        for j in range(max_items_per_transactions)])

print(records[0])

['shrimp', 'almonds', 'avocado', 'vegetables mix', 'green grapes', 'whole weat flour', 'yams', 'cottage cheese', 'energy drink', 'tomato juice', 'low fat yogurt', 'green tea', 'honey', 'salad', 'mineral water', 'salmon', 'antioxydant juice', 'frozen smoothie', 'spinach', 'olive oil']

In [30]:
association_rules = apriori(
    records, 
    min_support=0.0045, 
    min_confidence=0.2,
    min_lift=3,
    min_length=2)

association_results = list(association_rules)
print(f"Identified {len(association_results)} association rules")

Identified 48 association rules

In [70]:
for idx, item in enumerate(association_results):
    pair = item[0]
    items = [x for x in pair]
    print(f"Rule: {items[0]} -> {items[1]}")
    print(f"Support: {item[1]}")
    print(f"Confidence: {item[2][0][2]:0.3f}")
    print(f"Lift: {item[2][0][3]:0.3f}")
    print("===============================")

    if idx == 4:
        break

Rule: light cream -> chicken
Support: 0.004532728969470737
Confidence: 0.291
Lift: 4.844
===============================
Rule: escalope -> mushroom cream sauce
Support: 0.005732568990801226
Confidence: 0.301
Lift: 3.791
===============================
Rule: escalope -> pasta
Support: 0.005865884548726837
Confidence: 0.373
Lift: 4.701
===============================
Rule: ground beef -> herb & pepper
Support: 0.015997866951073192
Confidence: 0.323
Lift: 3.292
===============================
Rule: ground beef -> tomato sauce
Support: 0.005332622317024397
Confidence: 0.377
Lift: 3.841
===============================