In [3]:
import os

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from IPython.display import display, display_html, Markdown


sns.set(rc={'figure.figsize':(11.7,8.27)})
sns.set(style="ticks", context="talk")
plt.style.use("dark_background")

In [2]:
pd.__version__

'1.4.1'

In [4]:
def display_side_by_side(*args):
    html_str=''
    for df in args:
        html_str+=df.to_html()
    display_html(html_str.replace('table','table style="display:inline"'),raw=True)

In [5]:
display(Markdown('### Pandas inner merge on column - example'))
df1 = pd.DataFrame({'order_id': ['o1', 'o2', 'o3', 'o4', 'o5'],
                    'customer_id': ['c1', 'c2', 'c2', 'c3', 'c4']})
df2 = pd.DataFrame({'order_id': ['o1', 'o1', 'o2', 'o3', 'o4', 'o4', 'o5'],
                    'product_id': ['p1', 'p2', 'p1', 'p3', 'p4', 'p5', 'p5']})
merge_df = pd.merge(df1, df2, on='order_id', how='inner')

display(Markdown('#### df1 + df2 -> merged df'))
display_side_by_side(df1, df2, merge_df)

# display(Markdown('#### merged dfs'))
# display(merge_df)

### Pandas inner merge on column - example

#### df1 + df2 -> merged df

In [6]:
data_folder = '/Users/alex/Workspace/Datasets/OlistEcommercePublicDataset'

orders_df = pd.read_csv(os.path.join(data_folder, 'olist_orders_dataset.csv'))
reviews_df = pd.read_csv(os.path.join(data_folder, 'olist_order_reviews_dataset.csv'))
products_df = pd.read_csv(os.path.join(data_folder, 'olist_products_dataset.csv'))
order_items_df = pd.read_csv(os.path.join(data_folder, 'olist_order_items_dataset.csv'))
customer_df = pd.read_csv(os.path.join(data_folder, 'olist_customers_dataset.csv'))

In [7]:
display(orders_df[['order_id', 'customer_id']].head())
display(customer_df[['customer_id', 'customer_unique_id']].head())

                           order_id                       customer_id
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

                        customer_id                customer_unique_id
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

In [8]:
# from orders_df -> order_id, customer_id
# from customer_df -> customer_id, customer_unique_id
unique_id_df = pd.merge(orders_df[['order_id', 'customer_id']], customer_df[['customer_id', 'customer_unique_id']], on=['customer_id'], how='inner')
display(unique_id_df.head())

,order_id,customer_id,customer_unique_id
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,7c396fd4830fd04220f754e42b4e5bff
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,af07308b275d755c9edb36a90c618231
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,3a653a41f6f9fc3d2a113cf8398680e8
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,7c142cf63193a1473d2e66489a9ae977
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,72632f0f9dd73dfee390c9b22eb56dd6

In [9]:
display(orders_df[['order_id', 'customer_id']].head())
display(products_df[['product_id']].head())
display(order_items_df[['order_id', 'product_id']].head())

                           order_id                       customer_id
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

                         product_id
0  1e9e8ef04dbcff4541ed26657ea517e5
1  3aa071139cb16b67ca9e5dea641aaa2f
2  96bd76ec8810374ed1b65e291975717f
3  cef67bcfe19066a932b7673e239eb23d
4  9dc1a7de274444849c219cff195d0b71

                           order_id                        product_id
0  00010242fe8c5a6d1ba2dd792cb16214  4244733e06e7ecb4970a6e2683c13e61
1  00018f77f2f0320c557190d7a144bdd3  e5f2d52b802189ee658865ca93d83a8f
2  000229ec398224ef6ca0657da4fc703e  c777355d18b72b67abbeef9df44fd0fd
3  00024acbcdf0a6daa1e931b038114c75  7634da152a4610f1595efa32f14722fc
4  00042b26cf59d7ce69dfabb4e55b4fd9  ac6c3623068f30de03045865e4e10089

In [10]:
product_and_order_id_df = pd.merge(orders_df[['order_id', 'customer_id']], order_items_df[['order_id', 'product_id']], on=['order_id'], how='inner')
display(product_and_order_id_df.head())

,order_id,customer_id,product_id
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,87285b34884572647811a353c7ac498a
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,595fac2a385ac33a80bd5114aec74eb8
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,aa4383b373c6aca5d8797843e5594415
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,d0b61bfb1de832b15ba9d266ca96e5b0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,65266b2da20d04dbe00c5c2d3bb7859e

In [11]:
user_product_order_id_df = pd.merge(unique_id_df, product_and_order_id_df, on=['order_id', 'customer_id'], how='inner')
display(user_product_order_id_df.head())

,order_id,customer_id,customer_unique_id,product_id
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,7c396fd4830fd04220f754e42b4e5bff,87285b34884572647811a353c7ac498a
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,af07308b275d755c9edb36a90c618231,595fac2a385ac33a80bd5114aec74eb8
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,3a653a41f6f9fc3d2a113cf8398680e8,aa4383b373c6aca5d8797843e5594415
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,7c142cf63193a1473d2e66489a9ae977,d0b61bfb1de832b15ba9d266ca96e5b0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,72632f0f9dd73dfee390c9b22eb56dd6,65266b2da20d04dbe00c5c2d3bb7859e

In [12]:
display(reviews_df[['order_id', 'review_score']].head())

                           order_id  review_score
0  73fc7af87114b39712e6da79b0a377eb             4
1  a548910a1c6147796b98fdf73dbeba33             5
2  f9e4b658b201a9f2ecdecbb34bed034b             5
3  658677c97b385a9be170737859d3511b             5
4  8e6bfb81e283fa7e4f11123a3fb894f1             5

In [13]:
final_df = pd.merge(user_product_order_id_df, reviews_df[['order_id', 'review_score']], on=['order_id'], how='inner').drop(['customer_id', 'order_id'], axis=1)
display(final_df.head())

,customer_unique_id,product_id,review_score
0,7c396fd4830fd04220f754e42b4e5bff,87285b34884572647811a353c7ac498a,4
1,af07308b275d755c9edb36a90c618231,595fac2a385ac33a80bd5114aec74eb8,4
2,3a653a41f6f9fc3d2a113cf8398680e8,aa4383b373c6aca5d8797843e5594415,5
3,7c142cf63193a1473d2e66489a9ae977,d0b61bfb1de832b15ba9d266ca96e5b0,5
4,72632f0f9dd73dfee390c9b22eb56dd6,65266b2da20d04dbe00c5c2d3bb7859e,5

In [26]:
customer_id_dict = final_df['customer_unique_id'].to_dict()
product_id_dict = final_df['product_id'].to_dict()

customer_id_dict = {v: k for k, v in customer_id_dict.items()}
product_id_dict = {v: k for k, v in product_id_dict.items()}

KeyboardInterrupt:

In [14]:
rating_matrix = final_df.pivot_table(index='customer_unique_id', columns='product_id', values='review_score')

/Users/alex/miniconda3/envs/advanced/lib/python3.9/site-packages/pandas/core/reshape/reshape.py:134: PerformanceWarning: The following operation may generate 3105806869 cells in the resulting pandas object.
  warnings.warn(

In [19]:
rating_matrix.to_hdf('rating_matrix.h5', key='rating_matrix')

In [25]:
rating_matrix.isnull().sum()

product_id
00066f42aeeb9f3007548bb9d3f33c38    94720
00088930e925c41fd95ebfe695fd2655    94720
0009406fd7479715e4bef61dd91f2462    94720
000b8f95fcb9e0096488278317764d19    94719
000d9be29b5207b54e86aa1b1ac54872    94720
                                    ...
fff6177642830a9a94a0f2cba5e476d1    94719
fff81cc3158d2725c0655ab9ba0f712c    94720
fff9553ac224cec9d15d49f5a263411f    94720
fffdb2d0ec8d6a61f0a0a0db3f25b441    94716
fffe9eeff12fcbd74a2f2b007dde0c58    94720
Length: 32789, dtype: int64